services:
    n8n:
        image: n8nio/n8n
        restart: always
        ports:
            - "5678:5678"
        environment:
            - N8N_BASIC_AUTH_ACTIVE=true
            - N8N_BASIC_AUTH_USER=admin
            - N8N_BASIC_AUTH_PASSWORD=changeme
            - N8N_ENCRYPTION_KEY=your-secret-key
            - N8N_REQUEST_TIMEOUT=300000
        volumes:
            - n8n_data:/home/node/.n8n
            - ./documents:/documents:ro
        depends_on:
            - laravel
            - postgres

    # Da kein Laravel-spezifisches Dockerfile vorhanden ist, verwenden wir ein fertiges Image
    laravel:
        image: webdevops/php-apache:8.2-alpine
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./storage/app:/var/www/html/storage/app
        depends_on:
            - postgres
            - redis
            - meilisearch
        environment:
            - APP_ENV=production
            - APP_KEY=base64:1VnOOzaE+NNhzNMuH3mBKHAKarRwnLTfYwVah1y4MI0=
            - DB_CONNECTION=pgsql
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_DATABASE=knowledgebase
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret
            - REDIS_HOST=redis
            - MEILISEARCH_HOST=http://meilisearch:7700
            - DEEPSEEK_API_URL=https://api.deepseek.com

    postgres:
        image: postgres:14
        environment:
            POSTGRES_DB: knowledgebase
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./db/init:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"

    redis:
        image: redis:alpine
        volumes:
            - redis_data:/data
        ports:
            - "6379:6379"

    scraper:
        image: mcr.microsoft.com/playwright:v1.40.0-jammy
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        working_dir: /app
        command: sh -c "echo 'Scraper service ready with Playwright and Chrome installed' && tail -f /dev/null"

    meilisearch:
        image: getmeili/meilisearch:latest
        ports:
            - "7700:7700"
        volumes:
            - meilisearch_data:/data.ms
        environment:
            - MEILI_MASTER_KEY=your-meili-key

volumes:
    n8n_data:
    postgres_data:
    redis_data:
    meilisearch_data:
