# nixpacks.toml - Railway optimiert

[phases]
# Setup-Phase: Installiere alle benötigten Pakete
setup = { pkgs = [
    "php82",
    "php82Extensions.mysql",
    "php82Extensions.pgsql",    # PostgreSQL-Unterstützung
    "php82Extensions.gd",
    "php82Extensions.bcmath",
    "php82Extensions.zip",      # Für Composer
    "php82Extensions.curl",     # Für HTTP-Requests
    "php82Extensions.mbstring", # Für String-Handling
    "nodejs_18",
    "composer",
    "nginx",
    "procps",
    "findutils",                # Für find-Befehle
    "coreutils"                 # Für mkdir, chmod etc.
]}

# Install-Phase: Installiere Dependencies
install = { cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction",
    "npm ci --only=production --silent"
]}

# Build-Phase: Kompiliere Assets und bereite Laravel vor
build = { cmds = [
    "npm run build",
    "php artisan storage:link --force || true",
    "php artisan optimize:clear",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan event:cache"
]}

# Umgebungsvariablen
[variables]
NODE_ENV = "production"
APP_ENV = "production"
