# nixpacks.toml - Railway optimiert

[phases]
# Setup-Phase: Installiere alle benötigten Pakete
setup = { pkgs = [
    "php82",
    "php82Extensions.mysql",
    "php82Extensions.pgsql",
    "php82Extensions.gd",
    "php82Extensions.bcmath",
    "php82Extensions.zip",
    "php82Extensions.curl",
    "php82Extensions.mbstring",
    "nodejs_18",
    "composer",
    "nginx",
    "procps",
    "findutils",
    "coreutils"
]}

# Install-Phase: Installiere Dependencies
install = { cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction",
    "npm ci --only=production --silent"
]}

[variables]
NODE_ENV = "production"
APP_ENV = "production"
